<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <style>
        table tr td {
            font-size: 14px;
        }
        table tr > td {
            vertical-align: top;
            font-weight: bold;
        }
    </style>
</head>
<body bgcolor="#ffffff" style="padding:0;margin:0;">
    <table>
        <tr>
            <td><b>Название:</b></td>
            <td>Индивидуальный заказ</td>
        </tr>
        <tr>
            <td><b>Цена:</b></td>
            <td>0</td>
        </tr>
        <tr>
            <td><b>Image:</b></td>
            <td><?=$_SERVER['SERVER_NAME'].$data->image;?></td>
        </tr>
        <tr>
            <td><b>Заказ:</b></td>
            <td>
                <b>Name: </b><?=$this->data->name;?>
                <br/>
                <b>Mob: </b><?=$this->data->mob;?>
                <br/>
                <b>Text: </b><?=$this->data->text;?>
                <br/>
                <b>Image: </b><?=$this->data->image;?>
            </td>
        </tr>
        <tr>
            <td><b>Дата:</b></td>
            <td><?=date('d.m.Y H:i');?></td>
        </tr>
    </table>
</body>
</html>