<?php if ( $this->pageCount > 1): ?>
    <ul class="pagination">
        <?php if (isset($this->previous)): ?>
            <li><a href="#" onclick="return common.goToPage(<?=$this->previous?>);">&laquo;</a></li>
        <?php endif; ?>
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li><a href="#" onclick="return common.goToPage(<?= $page; ?>);"><?= $page; ?></a></li>
            <?php else: ?>
                <li class="active"><a href="#" onclick="return common.goToPage(<?= $page; ?>);"><?= $page; ?></a></li>
            <?php endif; ?>
        <?php endforeach; ?>
        <?php if (isset($this->next)): ?>
             <li><a href="#" onclick="return common.goToPage(<?=$this->next?>);">&raquo;</a></li>
        <?php endif; ?>
    </ul>
<?php endif; ?>