<?=$this->partial('blocks/menus/top.phtml');?>
<script type="text/javascript" src="/static/admin/js/jquery.tablednd_0_5.js"></script>
<script>
</script>
<style>
    .activeLink{
        border: 1px darkcyan dashed;
        padding: 3px;
        font-weight: bold;
    }
</style>
<table class="zebra" >
    <thead> 
        <tr> 
            <td style="width: 5%;"></td> 
            <td>
            </td>
            <td></td> 
            <td>
            </td>
            <td></td>
            <td></td>
        </tr>
    </thead>
<?php 
if (count($this->projectList->data)): ?>
	<?php $class = ''; ?>
	<tbody>
	<? $i = 0; ?>
	<? foreach ($this->projectList->data as $item): 
		$i++; ?>
		  <? ($class === 'grey') ? $class = '' : $class='grey'; ?>
		  <tr class="<?=$class; ?> id_<?=$item->getId()?>" rel="<?=$item->getIdPage()?>">
                <td style="text-align: right;"> 
                    <a href="<?=$this->url(array('id'=>$item->getId()), 'admin-faq-edit');?>" class="edit" style="float: left; display:block; margin-right: 10px;" title="Редактировать"><img src="/static/admin/images/edit.png" alt="Edit" width="16" height="16" /></a>
				</td>
				<td style="padding-left:10px;">
                    <?=Application_Model_Kernel_Content_Fields::getFieldByIdContentAndNameField($item->getContent()->getId(), 'contentName')->getFieldText()?>
                </td>
                <?php $StatusTitle = (!$item->getStatus()) ? 'Показать' : 'Скрыть'; ?>
                <td>
                </td>
                <td>
                </td>
                <td style="text-align: right;">
                    <a href="<?=$item->getRoute()->getUrl()?>" target="_black" title="Просмотр"><img src="/static/admin/images/eye.png" alt="" width="16" height="16"></a>&nbsp;&nbsp;
                    <a href="javascript:changeStatus(<?=$item->getIdPage()?>,1);" class="<?=$item->getStatus();?>" title="<?=$StatusTitle;?>">
                        <img class="page_status_<?=$item->getIdPage()?>" src="/static/admin/images/show_<?=$item->getStatus();?>.png" alt="" width="15" height="15">
                    </a>
                </td>
                <td style="text-align: left; padding-left: 10px;">
                    <a href="javascript:changeStatus(<?=$item->getIdPage();?>,2);" class="delete" title="Удалить"><img src="/static/admin/images/icon_delete.gif" alt="" width="9" height="8" /></a>
                </td>
		  </tr>
	<?php endforeach; ?>
	</tbody>
<?php endif; ?>
  </table> 
<?=$this->paginationControl($this->projectList->paginator, 'Sliding', 'blocks/paginator.phtml')?>
<input id="statusUrl" type="hidden" value="<?=$this->url(array(),'admin-faq-status')?>"/>