<?php //echo $this->contentPage['content']->getFieldText();?>

<? $this->headScript()->captureStart() ?>
function addView(id){
$.ajax({
type: "POST",
url: '/galleryowner/addview',
data: {"id":id},
success: function(result) {}
});
}
<? $this->headScript()->captureEnd() ?>
<div class="tov line">
    <?php foreach($this->publicList->data as $public): ?>
        <?php $publicContent = $public->getContent()->getFields();
        $publicContentText = strip_tags($publicContent['content']->getFieldText()); ?>

        <div class="tov__item">
            <a href="<?php echo $public->getRoute()->getUrl();?>" class="tov__img box">
                <img src="<?php echo $public->getPhoto1()->getPath('183', true)?>" style="max-height: 200px; max-width: 180px;" alt="<? echo isset($publicContent['img_alt'])?$publicContent['img_alt']->getFieldText():'';?>"/>
            </a>
            <a href="<?php echo $public->getRoute()->getUrl();?>" class="tov__name"><?php echo $publicContent['contentName']->getFieldText();?></a>
            <span class="tov__price"><span class="tov__num"><?=$public->getUserPrice()?></span> грн</span>
        </div>
    <?php endforeach; ?>
</div>
<?php echo $this->paginationControl($this->publicList->paginator, 'Sliding', 'block/paginator.phtml')?>