<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<section>
    <header>
        <h2>404 ошибка - страница не найдена</h2>
    </header>
    <article class="post">
        <br/>
<!--        <p><b>404 ошбика - страница не найдена</b></p>-->
        <p>Если вы уверены что страница это дложна существовать свяжитесь с нами и обьясните проблему и тогда мы ее решим в кратчайшие сроки. </p>
    </article>
</section>