<!DOCTYPE html>
<html lang="en">
<head>
    <title><?php echo $this->title; ?></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<?= $this->description ?>" />

    <?= $this->metaData ?>

    <meta name='yandex-verification' content='475a7886d322eee6' />

    <link rel="icon"
          type="image/png"
          href="/favicon.ico" />

    <link rel="stylesheet" href="/static/default/css/bootstrap.css" />
    <link rel="stylesheet" href="/static/default/css/justified-nav.css" />

    <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>

    <!--[if lt IE 9]>
    <script src="/static/default/js/html5shiv.js"></script>
    <script src="/static/default/js/respond.min.js"></script>
    <![endif]-->

    <script src="/static/default/js/common.js"></script>
    <script src="/static/default/js/bootstrap.min.js"></script>
    <script>
        $(function(){
            InitCommonFeatures();
        });
    </script>
    <?=$this->headScript()?>
    <script type="text/javascript" src="//vk.com/js/api/openapi.js?96"></script>
    <script type="text/javascript">
        VK.init({apiId: 3688273, onlyWidgets: true});
    </script>
</head>
<body>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
        ga('create', 'UA-11535685-11', 'vinylka.com.ua');
        ga('send', 'pageview');
    </script>
    <div id="fb-root"></div>
    <script>(function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s);
            js.id = id;
            js.src = "//connect.facebook.net/ru_RU/all.js#xfbml=1";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
    <div class="container">
        <? echo $this->partial('blocks/header.phtml', array('menu' => $this->menu, 'blocks'=>$this->blocks,'siteSetings'=>$this->siteSetings)) ?>
        <ol class="breadcrumb" style="background: none;">
            <? if (isset($this->mainCategory)): ?>
                <li><a href="http://vinylka.com.ua">Виниловые наклейки</a></li>
                <? if (isset($this->itemContent)): ?>
                    <li><a href="<? echo $this->mainCategory->getRoute()->getUrl(); ?>"><?php echo $this->mainCategoryContent['contentName']->getFieldText();?></a></li>
                    <li class="active"><?php echo $this->itemContent['contentName']->getFieldText();?></li>
                <? else: ?>
                    <li class="active"><?php echo $this->mainCategoryContent['contentName']->getFieldText();?></li>
                <? endif; ?>
            <? endif; ?>
        </ol>
        <div class="row row-offcanvas row-offcanvas-left">
            <div class="sidebar" id="sidebar" role="navigation" style="width: 180px;">
                <? echo $this->partial('blocks/menu.phtml', array('menu' => $this->menu, 'blocks'=>$this->blocks,'siteSetings'=>$this->siteSetings, 'item' => isset($this->itemContent)?true:false)) ?>
                <? echo $this->RemarketingBox($this->product_id); ?>
                <? echo $this->partial('blocks/social_media.phtml', array('menu' => $this->menu, 'blocks'=>$this->blocks,'siteSetings'=>$this->siteSetings, 'item' => isset($this->itemContent)?true:false)) ?>
            </div>
            <div class="main-content">
                <div class="row main-content__inner">
                    <div class="col-md-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-md-12">
                                        <? if (isset($this->filter) && $this->filter):?>
                                            <? $typres = Application_Model_Kernel_Category::getListParent();?>
                                            <div class="menu line">
                                                <div style="float:left;" id="btns_status">
                                                    <a class="btn btn-xs btn-default btn-success" data-status="0" onclick="return common.getByStatus(this);" href="">Все</a>
                                                    <a class="btn btn-xs btn-default" data-status="1" href="" onclick="return common.getByStatus(this);">В наличии</a>
                                                </div>
                                                <? foreach ($typres as $type): ?>
                                                    <? if(!$type->isStatusShow()) continue;?>
                                                    <? $typeContent = $type->getContent()->getFields();?>
                                                    <div class="types_inpt">
                                                        <label for="first"><?=$typeContent['contentName']->getFieldText();?></label>
                                                        <input type="checkbox" id="first" name="types" value="<?=$type->getId()?>"
                                                               onchange="common.goToPage(1);" />
                                                    </div>
                                                <?php endforeach; ?>
                                            </div>
                                        <? else: ?>
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <? if (isset($this->itemContent)): ?>
                                                        <h1 style="margin: 0px; font-size: 20px;"><?php echo $this->itemContent['contentName']->getFieldText();?></h1>
                                                    <? endif; ?>
                                                </div>
                                            </div>
                                        <? endif; ?>
                                    </div>
                                </div>
                            </div>
                            <div class="panel-body box">
                                <div class="row">
                                    <?php echo $this->layout()->content ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->partial('blocks/footer.phtml', array(
                                                              'blocks'=>$this->blocks,
                                                              'siteSetings'=>$this->siteSetings,
                                                              'text'=> $this->text
                                                         )) ?>
    </div>

    <div class="modal fade" id="myModalIndividual" tabindex="-1" role="dialog" aria-labelledby="myModalIndividual" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <form data-action="<?=$this->url(array(), 'default-ajax-individual_order')?>"
                      action="<?=$this->url(array(), 'default-post-individual_order')?>"
                      enctype="multipart/form-data"
                      id="form_individual_order"
                      method="POST"
                    >
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="myModalIndividualLabel">Оформление вашего заказа</h4>
                    </div>
                    <div class="modal-body" style="padding-bottom: 0px;">
                        <table class="table table-bordered">
                            <thead>
                            <tr class="active">
                                <th>Контактные данные</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>
                                    <div class="form-group">
                                        <label for="exampleInputName">Ваше имя и фамилия</label>
                                        <input type="text" required="required" class="form-control" value="" name="name" id="exampleInputName" placeholder="Александр Александрович">
                                        <input type="text" class="b-input" value="" name="last_name" id="last_name_ind"/>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="form-group">
                                        <label for="exampleInputIndMob">Номер мобильного телефона</label>
                                        <input required="required" type="text" class="form-control" value="" id="exampleInputIndMob" placeholder="+380509999999" name="mob">
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputIndEmail">Email:</label>
                                        <input type="email" class="form-control" value="" id="exampleInputIndEmail" placeholder="my@example.com" name="email">
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="form-group">
                                        <label for="exampleInputFile">Ссылка на картинку наклейки</label>
                                        <input type="text" required="required" class="form-control" value="" name="image" id="exampleInputFile" placeholder="http://some/image.jpg">
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <label class="b-label">Примечание к заказу</label>
                                    <textarea class="form-control" rows="3" value="" name="text"></textarea>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                        <div class="alert alert-danger error_block">
                            <div class="b-input-i"></div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                        <button type="button" class="btn btn-primary" onclick="return common.submitIndividualOrder('#form_individual_order')">Заказать</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="modal fade" id="myModalSenks">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Заказ сделан</h4>
                </div>
                <div class="modal-body">
                    <p>Ваш заказ добавлен в обработку.</p>
                    <p>Спасибо за покупку в Vinylka.com.ua</p>
                    <p><a href="http://vinylka.com.ua">На главную</a></p>
                </div>
            </div>
        </div>
    </div>
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript">
        (function (d, w, c) {
            (w[c] = w[c] || []).push(function() {
                try {
                    w.yaCounter25049903 = new Ya.Metrika({id:25049903,
                        webvisor:true,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true});
                } catch(e) { }
            });

            var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
            s.type = "text/javascript";
            s.async = true;
            s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

            if (w.opera == "[object Opera]") {
                d.addEventListener("DOMContentLoaded", f, false);
            } else { f(); }
        })(document, window, "yandex_metrika_callbacks");
    </script>
    <noscript><div><img src="//mc.yandex.ru/watch/25049903" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
    <!-- Код Google для тегу ремаркетингу -->
    <!--------------------------------------------------
    Теги ремаркетингу не можна пов’язувати з особистою інформацією або розміщувати на сторінках, пов’язаних із категоріями делікатного характеру. Докладніші відомості та вказівки з налаштування тегу див. за адресою http://google.com/ads/remarketingsetup
    --------------------------------------------------->
    <script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = 946347855;
        var google_custom_params = window.google_tag_params;
        var google_remarketing_only = true;
        /* ]]> */
    </script>
    <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
    </script>
    <noscript>
        <div style="display:inline;">
            <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/946347855/?value=0&amp;guid=ON&amp;script=0"/>
        </div>
    </noscript>

    <script type="text/javascript">(window.Image ? (new Image()) : document.createElement('img')).src = location.protocol + '//vk.com/rtrg?r=pSf7Rx0/bvVs9HpUYG9TBcR/YX2s7ogSyGK2SAwQ3JONiXYmjfWpDxo35WAaPq/Yk4n6X9yDgoIQskSRfGXAIAdr4rrbF7XM8O2IiqGvZ*4pNWfmXsyEIDK0wBuZDd7bQ07ty5RGmxeEz82dpvOkSBrmbl6tsnpL6I9i/pPeE94-';</script>
    <!-- Facebook Pixel Code -->
    <script>
        !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
            n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
            n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
            t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
            document,'script','//connect.facebook.net/en_US/fbevents.js');

        fbq('init', '1642132142726095');
        fbq('track', "PageView");</script>
    <noscript><img height="1" width="1" style="display:none"
                   src="https://www.facebook.com/tr?id=1642132142726095&ev=PageView&noscript=1"
            /></noscript>
    <!-- End Facebook Pixel Code -->
</body>
</html>