<!DOCTYPE html>
<html lang="en">
<head>
    <title><?php echo $this->title; ?></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<?= $this->description ?>" />

    <link rel="stylesheet" href="/static/default/css/bootstrap.css" />
    <link rel="stylesheet" href="/static/default/css/justified-nav.css" />

    <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>

    <!--[if lt IE 9]>
    <script src="/static/default/js/html5shiv.js"></script>
    <script src="/static/default/js/respond.min.js"></script>
    <![endif]-->

    <script src="/static/default/js/common.js"></script>
    <script src="/static/default/js/bootstrap.min.js"></script>
    <script>
        $(function(){
            InitCommonFeatures();
        });
    </script>
    <?=$this->headScript()?>
    <script type="text/javascript" src="//vk.com/js/api/openapi.js?96"></script>
    <script type="text/javascript">
        VK.init({apiId: 3688273, onlyWidgets: true});
    </script>
</head>
<body>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
        ga('create', 'UA-11535685-11', 'vinylka.com.ua');
        ga('send', 'pageview');
    </script>
    <div id="fb-root"></div>
    <script>(function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s);
            js.id = id;
            js.src = "//connect.facebook.net/ru_RU/all.js#xfbml=1";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
    <div class="container">
        <? echo $this->partial('blocks/header.phtml', array('menu' => $this->menu, 'blocks'=>$this->blocks,'siteSetings'=>$this->siteSetings)) ?>
        <ol class="breadcrumb" style="background: none;">
            <? if (isset($this->mainCategory)): ?>
                <li><a href="http://vinylka.com.ua">Виниловые наклейки</a></li>
                <? if (isset($this->itemContent)): ?>
                    <li><a href="<? echo $this->mainCategory->getRoute()->getUrl(); ?>"><?php echo $this->mainCategoryContent['contentName']->getFieldText();?></a></li>
                    <li class="active"><?php echo $this->itemContent['contentName']->getFieldText();?></li>
                <? else: ?>
                    <li class="active"><?php echo $this->mainCategoryContent['contentName']->getFieldText();?></li>
                <? endif; ?>
            <? endif; ?>
        </ol>
        <div class="row row-offcanvas row-offcanvas-left">
            <? echo $this->partial('blocks/menu.phtml', array('menu' => $this->menu, 'blocks'=>$this->blocks,'siteSetings'=>$this->siteSetings)) ?>
            <div class="col-xs-12 col-sm-9">
<!--                <div class="jumbotron">-->
<!--                    <h1>Marketing stuff!</h1>-->
<!--                    <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet.</p>-->
<!--                    <p><a class="btn btn-lg btn-success" href="#">Get started today</a></p>-->
<!--                </div>-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-md-12">
                                        <? if (isset($this->filter) && $this->filter):?>
                                            <? $typres = Application_Model_Kernel_Category::getListParent();?>
                                            <div class="menu line">
                                                <? foreach ($typres as $type): ?>
                                                    <? if(!$type->isStatusShow()) continue;?>
                                                    <? $typeContent = $type->getContent()->getFields();?>
                                                    <div class="types_inpt">
                                                        <label for="first"><?=$typeContent['contentName']->getFieldText();?></label>
                                                        <input type="checkbox" id="first" name="types" value="<?=$type->getId()?>"
                                                               onchange="common.goToPage(1);" />
                                                    </div>
                                                <?php endforeach; ?>
                                            </div>
                                        <? else: ?>
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <? if (isset($this->itemContent)): ?>
                                                        <h1 style="margin: 0px; font-size: 26px;"><?php echo $this->itemContent['contentName']->getFieldText();?></h1>
                                                    <? endif; ?>
                                                </div>
                                            </div>
                                        <? endif; ?>
                                    </div>
                                </div>
                            </div>
                            <div class="panel-body box">
                                <div class="row">
                                    <?php echo $this->layout()->content ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->partial('blocks/footer.phtml', array(
                                                              'blocks'=>$this->blocks,
                                                              'siteSetings'=>$this->siteSetings,
                                                              'text'=> $this->text
                                                         )) ?>
    </div>
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript">
        (function (d, w, c) {
            (w[c] = w[c] || []).push(function() {
                try {
                    w.yaCounter21420952 = new Ya.Metrika({id:21420952,
                        webvisor:true,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true});
                } catch(e) { }
            });

            var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
            s.type = "text/javascript";
            s.async = true;
            s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

            if (w.opera == "[object Opera]") {
                d.addEventListener("DOMContentLoaded", f, false);
            } else { f(); }
        })(document, window, "yandex_metrika_callbacks");
    </script>
    <noscript><div><img src="//mc.yandex.ru/watch/21420952" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
</body>
</html>