<?php //echo $this->contentPage['content']->getFieldText();?>

<? $this->headScript()->captureStart() ?>
    $(function() {
        $('#stic_list').val("<?=$this->url(array('idCat'=>$this->page->getIdCat()),'default-ajax-more_stikers');?>");
    });
<? $this->headScript()->captureEnd() ?>

<? $this->mainCategory = $this->page;?>
<? $this->mainCategoryContent = $this->contentPage;?>

<div class="row">
    <? echo $this->ListItems($this->publicList->data); ?>
</div>
<?php echo $this->paginationControl($this->publicList->paginator, 'Sliding', 'block/paginator.phtml')?>