<div class="ftr-i">
    <div class="ftr line">
        <? echo $this->text;?>
        <p class="ftr__copy"><?=date('Y')?> © Интернет-магазин «<a style="text-decoration: underline;" href="http://vinylka.com.ua">Vinylka.com.ua</a>»</p>
        <br/>
        <!--LiveInternet counter--><script type="text/javascript"><!--
            document.write("<a href='http://www.liveinternet.ru/click' "+
                "target=_blank><img src='//counter.yadro.ru/hit?t26.6;r"+
                escape(document.referrer)+((typeof(screen)=="undefined")?"":
                ";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
                    screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
                ";"+Math.random()+
                "' alt='' title='LiveInternet: показано число посетителей за"+
                " сегодня' "+
                "border='0' width='88' height='15'><\/a>")
            //--></script><!--/LiveInternet-->
    </div>
</div>
<input type="hidden" id="stic_list" value="<?=$this->url(array(),'default-ajax-more_stikers');?>"/>