<? $category = $this->ShowCategorys(); ?>
<div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
    <div class="list-group">
        <? foreach ($category as $cat):?>
            <? $catContent = $cat->getContent()->getFields();?>
            <?php if(isset($this->menu)&&$this->menu==$cat->getRoute()->getUrl()):?>
                <span class="list-group-item active"><?=$catContent['contentName']->getFieldText();?></span>
            <? else: ?>
                <a href="<?=$cat->getRoute()->getUrl();?>" class="list-group-item"><?=$catContent['contentName']->getFieldText();?></a>
            <?php endif;?>
        <? endforeach; ?>
    </div>
</div>