<? $category = $this->ShowCategorys(); ?>
<div class="sidebar" id="sidebar" role="navigation" style="width: 280px;">
    <div class="row">
        <div class="col-md-12">
            <div class="list-group">
                <? foreach ($category as $cat):?>
                    <? $catContent = $cat->getContent()->getFields();?>
                    <?php if(isset($this->menu)&&$this->menu==$cat->getRoute()->getUrl() ):?>
                        <? if (!$this->item): ?>
                            <span class="list-group-item active"><?=$catContent['contentName']->getFieldText();?></span>
                        <? else: ?>
                            <a class="list-group-item active" href="<?=$cat->getRoute()->getUrl();?>"><?=$catContent['contentName']->getFieldText();?></a>
                        <? endif; ?>
                    <? else: ?>
                        <a href="<?=$cat->getRoute()->getUrl();?>" class="list-group-item"><?=$catContent['contentName']->getFieldText();?></a>
                    <?php endif;?>
                <? endforeach; ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <script type="text/javascript" src="//vk.com/js/api/openapi.js?105"></script>

                    <!-- VK Widget -->
                    <div id="vk_groups"></div>
                    <script type="text/javascript">
                        VK.Widgets.Group("vk_groups", {mode: 0, width: "auto", height: "230", color1: 'FFFFFF', color2: '3A7A2A', color3: '5BA563'}, 62731628);
                    </script>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="fb-like-box" data-width="230" data-height="230" data-href="https://www.facebook.com/pages/Vinylkacomua/339698922837376" data-colorscheme="light" data-show-faces="true" data-header="false" data-stream="false" data-show-border="false"></div>
                </div>
            </div>
        </div>
    </div>
</div>