<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<? $this->itemContent = $this->contentPage; ?>
<div class="col-md-12">
    <? foreach($this->faqs->data as $faq): ?>
        <? $faqContent = $faq->getContent()->getFields();?>
        <? $content = strip_tags($faqContent['content']->getFieldText()); ?>
        <div class="row">
            <div class="col-md-4">
                <a href="<?=$faq->getRoute()->getUrl();?>">
                    <img src="<?=$faq->getPhoto1()->getPath('200', true)?>" alt="<?=$faqContent['img_alt']->getFieldText();?>" class="img-thumbnail"/>
                </a>
            </div>
            <div class="col-md-8">
                <a href="<?=$faq->getRoute()->getUrl();?>">
                    <h4><?=$faqContent['contentName']->getFieldText();?></h4>
                </a>
                <p><?=Application_Model_Kernel_TextRedactor::cutText($content, 350)?>
                <a href="<?=$faq->getRoute()->getUrl();?>"><small>[...]</small></a></p>
            </div>
        </div>
        <hr/>
    <? endforeach; ?>
    <div class="row">
        <div class="col-md-12">
            <?=$this->contentPage['content']->getFieldText()?>
        </div>
    </div>
</div>