<?= $this->partial('blocks/menus/top.phtml'); ?>
<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<form action="<?= $this->url() ?>" method="post" id="PageForm">
    <table class="zebra edit">
        <tr class="grey">
            <td width="193" class="first">ФИО:</td>
            <td>
                <input type="text" name="name" value="<?=$this->order->getName(); ?>"/>
            </td>
        </tr>
        <tr class="grey">
            <td width="193" class="first">Телефон:<br/> в формате +380 (99) 999-9999</td>
            <td>
                <input type="text" name="phone" value="<?=$this->order->getPhone(); ?>"/>
            </td>
        </tr>
        <tr class="grey">
            <td width="193" class="first">Email:</td>
            <td>
                <input type="email" name="email" value="<?=$this->order->getEmail(); ?>" />
            </td>
        </tr>
        <tr class="grey">
            <td width="193" class="first">Текст:</td>
            <td>
                <textarea name="text"><?=$this->order->getText(); ?></textarea>
            </td>
        </tr>
        <tr class="grey">
            <td width="193" class="first">Цена:</td>
            <td>
                <input type="text" name="userPrice" value="<?=$this->order->getPriceUser(); ?>"/>
            </td>
        </tr>
        <tr class="grey">
            <td width="193" class="first">Урл Наклейки:</td>
            <td>
                <? if ($this->order->getIdProduct()): ?>
                <a href="<?=$this->order->getProduct()->getRoute()->getUrl(); ?>"><?=$this->order->getProduct()->getRoute()->getUrl(); ?></a>
                <? endif; ?>
            </td>
        </tr>
        <tr class="grey">
            <td width="193" class="first">Доставка:</td>
            <td>
                <input type="text" name="delivery" value="<?=$this->order->getDeliveryType(); ?>"/>
            </td>
        </tr>
        <tr class="">
            <td width="193" class="first">Статус товара:</td>
            <td>
                <select name="status">
                    <option value="0" <? if (0==$this->order->getStatus()): ?>selected="selected"<? endif; ?>>Новый</option>
                    <option value="4" <? if (4==$this->order->getStatus()): ?>selected="selected"<? endif; ?>>В работе</option>
                    <option value="5" <? if (5==$this->order->getStatus()): ?>selected="selected"<? endif; ?>>Отправлено</option>
                    <option value="1" <? if (1==$this->order->getStatus()): ?>selected="selected"<? endif; ?>>Успешно закрыт</option>
                    <option value="2" <? if (2==$this->order->getStatus()): ?>selected="selected"<? endif; ?>>Отказ</option>
                    <option value="3" <? if (3==$this->order->getStatus()): ?>selected="selected"<? endif; ?>>Не обработан</option>
                </select>
            </td>
        </tr>
        <tr class="grey">
            <td colspan="2">
                <div class="m10 centerButton">
                    <a href="javascript:SubmitPageFrom();" class="button_blue">Сохранить</a>
                    <a href="<?=$this->url(array('page'=>1),'admin-order-index') ?>" class="button_grey">Отменить</a>
                </div>
            </td>
        </tr>
    </table>
</form>
